$ANSIBLE_VAULT;1.1;AES256
66353036363632636161343530356362303862313964333136613838306137613038333864303562
3733393035313136663237623238386233333834663939340a653562383637393430643736383130
31323135643536333532373066383939313464386265346333636331653537323637366237313432
6330643163653739310a623261383937373431343535626136663565656535613230303032323838
32646635353338383864346461613336303930626538323761663931363636643839313134343137
39386135313835636131346664363966343735616239313332343530363231643536386461313865
64383266316435636262383362376536623231333137366637393031326536373830653633383432
66653962636636616463
